baseURL: https://example.com/
canonifyURLs: yes
relativeURLs: yes
uglyURLs: no
theme: hugo-theme-relearn
defaultContentLanguage: ru
title: Hugo Relearn Documentation
outputs:
  home:
    - HTML
    - RSS
    - PRINT
    - SEARCH
    - SEARCHPAGE
  page:
    - HTML
    - RSS
    - PRINT
  section:
    - HTML
    - RSS
    - PRINT
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    guessSyntax: no
    noClasses: no
server:
  headers:
    - for: '**.html'
      values:
        X-UA-Compatible: IE=edge
languages:
  en:
    languageName: English
    menu:
      shortcuts:
        - name: <i class='fas fa-fw fa-camera'></i> Showcases
          pageRef: showcase/
          weight: 11
        - identifier: hugodoc
          name: <i class='fas fa-fw fa-bookmark'></i> Hugo Documentation
          url: https://gohugo.io/
          weight: 20
        - name: <i class='fas fa-fw fa-tags'></i> Tags
          pageRef: tags/
          weight: 40
    params:
      landingPageName: <i class='fas fa-home'></i> Home
    title: Hugo Relearn Theme
    weight: 1
    params:
      landingPageName: <i class='fas fa-home'></i> Arrr! Home
    title: Cap'n Hugo Relearrrn Theme
    weight: 2
module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: data
      target: data
    - source: i18n
      target: i18n
    - source: ../images
      target: static/images
    - source: static/images
      target: static/images
    - source: layouts
      target: layouts
    - source: static
      target: static
params:
  additionalContentLanguage: en
  author: Sören Weber
  breadcrumbSeparator: '>'
  collapsibleMenu: yes
  description: Documentation for Hugo Relearn Theme
  disableBreadcrumb: no
  disableInlineCopyToClipBoard: yes
  disableLandingPageButton: yes
  disableNextPrev: no
  disableSeoHiddenPages: yes
  editURL: https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content/
  mermaidInitialize: '{ "securityLevel": "loose" }'
  mermaidZoom: yes
  showVisitedLinks: yes
  themeVariant:
    - auto
    - relearn-bright
    - relearn-light
    - relearn-dark
    - learn
    - neon
    - blue
    - green
    - red
  themeVariantAuto:
    - relearn-light
    - relearn-dark
  titleSeparator: '::'
