baseURL: https://example.com/
canonifyURLs: yes
relativeURLs: yes
uglyURLs: no
theme: hugo-theme-relearn
languageCode: en
defaultContentLanguage: en
title: Hugo Relearn Documentation
params:
  themeVariant:
    - auto
    - relearn-bright
    - relearn-light
    - relearn-dark
    - learn
    - neon
    - blue
    - green
    - red
  themeVariantAuto:
    - relearn-light
    - relearn-dark
  titleSeparator: '::'
