baseURL: https://example.com/
canonifyURLs: yes
relativeURLs: yes
uglyURLs: no
theme: hugo-theme-relearn
languageCode: en
defaultContentLanguage: en
title: Hugo Relearn Documentation
outputs:
  home:
    - HTML
    - RSS
    - PRINT
    - SEARCH
    - SEARCHPAGE
  page:
    - HTML
    - RSS
    - PRINT
  section:
    - HTML
    - RSS
    - PRINT
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    guessSyntax: no
    noClasses: no
server:
  headers:
    - for: '**.html'
      values:
        X-UA-Compatible: IE=edge

params:
  themeVariant:
    - auto
    - relearn-bright
    - relearn-light
    - relearn-dark
    - learn
    - neon
    - blue
    - green
    - red
  themeVariantAuto:
    - relearn-light
    - relearn-dark
  titleSeparator: '::'
